name: Build & Deploy Ecommerce for Multi-Sellers App
on:
  push:
    branches:
      - main
      - dev
jobs:
  build-deploy:
    name: Build & Deploy Ecommerce for Multi-Sellers App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Commit changes
        if: ${{ job.status == success() }}
        run: |
          git config --global user.email "rachidbenkitou2021@gmail.com"
          git config --global user.name "Your Name"
          git commit -am "Build successful"
          git push
